"""
Script Generator

Generates bash scripts for executing CDK imports.
"""

from pathlib import Path
from typing import List, Dict, Any


class ScriptGenerator:
    """Generate import scripts for CDK"""

    def __init__(self, cdk_project_dir: Path, skip_preview: bool = False):
        self.cdk_project_dir = cdk_project_dir
        self.skip_preview = skip_preview

    def generate_stack_import_script(
        self, stack_name: str, org_metadata: Dict[str, Any]
    ) -> str:
        """
        Generate import script for a single stack

        Args:
            stack_name: Name of the stack
            org_metadata: Organization metadata

        Returns:
            Bash script content
        """
        script = f"""#!/bin/bash
# Import script for {stack_name}
# Generated by cdk-import-config-generator

set -e  # Exit on error

echo "========================================="
echo "CDK Import: {stack_name}"
echo "========================================="
echo ""

# Change to CDK project directory
cd "{self.cdk_project_dir.absolute()}"

# Path to mapping file (relative to scripts directory)
MAPPING_FILE="../import-mappings/{stack_name.lower()}-mappings.json"

echo "📋 Stack: {stack_name}"
echo "📁 Mapping file: $MAPPING_FILE"
echo ""

# Verify mapping file exists
if [ ! -f "$MAPPING_FILE" ]; then
    echo "❌ Error: Mapping file not found: $MAPPING_FILE"
    exit 1
fi

# Preview mode
echo "🔍 Running preview first (dry-run)..."
echo ""
cdk import {stack_name} \\
    --resource-mapping "$MAPPING_FILE" \\
    --execute false

echo ""
echo "========================================="
echo "Preview complete!"
echo "========================================="
echo ""
echo "Review the output above carefully."
echo "If everything looks correct, proceed with the import."
echo ""
read -p "Proceed with import? (yes/no): " -r
echo ""

if [[ ! $REPLY =~ ^[Yy]es$ ]]; then
    echo "Import cancelled."
    exit 0
fi

# Execute import
echo "🚀 Importing {stack_name}..."
echo ""
cdk import {stack_name} \\
    --resource-mapping "$MAPPING_FILE"

echo ""
echo "========================================="
echo "✅ Import complete for {stack_name}!"
echo "========================================="
echo ""
echo "Next steps:"
echo "  1. Verify with: cdk diff {stack_name}"
echo "  2. Should show no changes"
echo ""
"""
        return script

    def generate_import_all_script(self, ordered_stacks: List[str]) -> str:
        """
        Generate script to import all stacks in dependency order

        Args:
            ordered_stacks: List of stack names in deployment order

        Returns:
            Bash script content
        """
        script = """#!/bin/bash
# Import all stacks in dependency order
# Generated by cdk-import-config-generator

set -e  # Exit on error

echo "========================================="
echo "CDK Import All Stacks"
echo "========================================="
echo ""
echo "This will import all stacks in dependency order:"
"""

        for i, stack_name in enumerate(ordered_stacks, 1):
            script += f'echo "  {i}. {stack_name}"\n'

        script += """echo ""
echo "⚠️  IMPORTANT:"
echo "  - Ensure you have reviewed the import mappings"
echo "  - Run preview scripts first if available"
echo "  - Have CloudFormation state backed up"
echo "  - This operation will modify CloudFormation"
echo ""
read -p "Ready to proceed? (yes/no): " -r
echo ""

if [[ ! $REPLY =~ ^[Yyes$ ]]; then
    echo "Import cancelled."
    exit 0
fi

echo "🚀 Starting import process..."
echo ""

"""

        for stack_name in ordered_stacks:
            script += f"""
echo "========================================="
echo "Importing {stack_name}..."
echo "========================================="
echo ""

./import-{stack_name.lower()}.sh

echo ""
"""

        script += """
echo "========================================="
echo "✅ All stacks imported successfully!"
echo "========================================="
echo ""
echo "Next steps:"
echo "  1. cd ../{self.cdk_project_dir.name}"
echo "  2. cdk diff --all"
echo "  3. Should show no changes"
echo ""
"""
        return script

    def generate_preview_all_script(self, ordered_stacks: List[str]) -> str:
        """
        Generate script to preview all imports (dry-run)

        Args:
            ordered_stacks: List of stack names in deployment order

        Returns:
            Bash script content
        """
        script = f"""#!/bin/bash
# Preview all imports (dry-run mode)
# Generated by cdk-import-config-generator

set -e  # Exit on error

echo "========================================="
echo "CDK Import Preview (Dry Run)"
echo "========================================="
echo ""
echo "This will preview what will be imported WITHOUT making any changes."
echo ""

# Change to CDK project directory
cd "{self.cdk_project_dir.absolute()}"

"""

        for stack_name in ordered_stacks:
            script += f"""
echo "========================================="
echo "Preview: {stack_name}"
echo "========================================="
echo ""

MAPPING_FILE="../import-mappings/{stack_name.lower()}-mappings.json"

if [ ! -f "$MAPPING_FILE" ]; then
    echo "❌ Error: Mapping file not found: $MAPPING_FILE"
    exit 1
fi

cdk import {stack_name} \\
    --resource-mapping "$MAPPING_FILE" \\
    --execute false

echo ""
"""

        script += """
echo "========================================="
echo "✅ Preview complete!"
echo "========================================="
echo ""
echo "Review the output above carefully."
echo "If everything looks correct, run ./import-all.sh to execute the import."
echo ""
"""
        return script
